name: Docker Push Action

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test-and-docker-image-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker install check
        run: docker version

      - name: Build and test frontend
        run: |
          docker build -t jheehg/react-test-app -f ./frontend/Dockerfile.dev ./frontend
          docker run -e CI=true jheehg/react-test-app npm run test

      - name: Build docker images
        run: |
          docker build -t jheehg/docker-frontend ./frontend
          docker build -t jheehg/docker-nginx ./nginx
          docker build -t jheehg/docker-backend ./backend

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push jheehg/docker-frontend
          docker push jheehg/docker-backend
          docker push jheehg/docker-nginx
